Controllers/DepartmentController.cs
using Company.BLL.Interfaces;
using Company.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Company.PL.Controllers
{
    [Authorize(Roles = "Admin, HR")]
    public class DepartmentController : Controller
    {
        private readonly IDepartmentRepository _repository;

        public DepartmentController(IDepartmentRepository repository)
        {
            _repository = repository;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var data = await _repository.GetAll();
            return View(data);
        }
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();
            var department = await _repository.Get(id);

            if(department == null)
                return NotFound();

            return View(department);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Department department)
        {
            if (ModelState.IsValid)
            {
                await _repository.Create(department);
                TempData["Message"] = "Department is Created Successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
                return NotFound();
            var department = await _repository.Get(id);

            if (department == null)
                return NotFound();

            return View(department);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id,Department department)
        {
            if(id != department.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    await _repository.Update(department);
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return View(department);
                }
            }

            return View(department);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();
            var department = await _repository.Get(id);

            if (department == null)
                return NotFound();

            return View(department);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id,Department department)
        {
            if (id != department.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    await _repository.Delete(department);
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return View(department);
                }
            }

            return View(department);
        }

    }
}

Controllers/EmployeeController.cs
using AutoMapper;
using Company.BLL.Interfaces;
using Company.DAL.Entities;
using Company.PL.Helper;
using Company.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using System.Data;

namespace Company.PL.Controllers
{
    [Authorize(Roles = "Admin, HR")]
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper mapper;

        public EmployeeController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            this.unitOfWork = unitOfWork;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index(string SearchValue = "")
        {
            if (string.IsNullOrEmpty(SearchValue))
            {
                var employess = await unitOfWork.EmployeeRepository.GetAll();
                var mappedEmployee = mapper.Map<IEnumerable<EmployeeViewModel>>(employess);
                return View(mappedEmployee);
            }
            else
            {
                var employess = await unitOfWork.EmployeeRepository.Search(SearchValue);
                var mappedEmployee = mapper.Map<IEnumerable<EmployeeViewModel>>(employess);
                return View(mappedEmployee);
            }
        }

        public async Task<IActionResult> Create()
        {
            // 1. ViewData 
            // is a dictionary object [.Net Framework 3.5 ]
            // helps us to transfer the data from controller to view
            //ViewData["Message"] = "Hello World";

            // 2. ViewBag is a dynamic property [.Net Framework 4]
            // helps us to transfer the data from controller to view

            //ViewBag.Message = "Hello World 2";

            // 3.TempData
            // is a dictionary object [.Net Framework 3.5 ]
            // it is used to transfer data between to consecunsive requests
            ViewBag.Departments = await unitOfWork.DepartmentRepository.GetAll();

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel employee)
        {
            //var mappedEmployee = new Employee()
            //{
            //    Id = employee.Id,
            //    Name = employee.Name,
            //    Address = employee.Address,
            //    Age = employee.Age,
            //    DepartmentId = employee.DepartmentId,
            //    Email = employee.Email,
            //    HireDate = employee.HireDate,
            //    Salary = employee.Salary,
            //    PhoneNumber = employee.PhoneNumber,
            //    IsActive = employee.IsActive 
            //};

            if (ModelState.IsValid)
            {
                employee.ImageName = DocumentSettings.UploadFile(employee.Image, "imgs");

                var mappedEmployee = mapper.Map<Employee>(employee);
                await unitOfWork.EmployeeRepository.Create(mappedEmployee);
                return RedirectToAction("Index");
            }
            ViewBag.Departments = await unitOfWork.DepartmentRepository.GetAll();
            return View(employee);

        }

        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
                return NotFound();

            var employee = await unitOfWork.EmployeeRepository.Get(id);
            if (employee == null)
                return NotFound();

            var mappedEmployee = mapper.Map<EmployeeViewModel>(employee);


            ViewBag.Departments = await unitOfWork.DepartmentRepository.GetAll();

            return View(mappedEmployee);

        }

        [HttpPost]
        public async Task<IActionResult> Update(int? id, EmployeeViewModel employee)
        {
            if(id != employee.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var mappedEmp = mapper.Map<Employee>(employee);

                    await unitOfWork.EmployeeRepository.Update(mappedEmp);

                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return View(employee);
                }
            }

            ViewBag.Departments = await unitOfWork.DepartmentRepository.GetAll();

            return View(employee);
        }
    }
}

Controllers/RolesController.cs
using Company.DAL.Entities;
using Company.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace Company.PL.Controllers
{
    [Authorize(Roles = "Admin, HR")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _roleManager.CreateAsync(role);

                    if (result.Succeeded)
                        return RedirectToAction("Index");

                    foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);
                }
                catch (Exception)
                {

                    throw;
                }
            }
             return View(role);
        }

        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
            if (id == null)
                return NotFound();

            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
                return NotFound();

            return View(viewName, role);
        }

        public async Task<IActionResult> Update(string id)
        {
            return await Details(id, "Update");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id, IdentityRole role)
        {
            if (id != role.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var appRole = await _roleManager.FindByIdAsync(id);

                    appRole.Name = role.Name;
                    appRole.NormalizedName = role.Name.ToUpper();

                    var result = await _roleManager.UpdateAsync(appRole);

                    if (result.Succeeded)
                        return RedirectToAction("Index");

                    foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(role);
        }

        public async Task<IActionResult> Delete(string id, IdentityRole role)
        {
            if (id != role.Id)
                return BadRequest();

            try
            {
                var appRole = await _roleManager.FindByIdAsync(id);

                var result = await _roleManager.DeleteAsync(appRole);

                if (result.Succeeded)
                    return RedirectToAction("Index");

                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role == null)
                return NotFound();

            ViewBag.RoleId = roleId;

            var users = new List<UserInRoleViewModel>();

            foreach (var user in _userManager.Users)
            {
                var userInRole = new UserInRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                    userInRole.IsSelected = true;
                else 
                    userInRole.IsSelected = false;

                users.Add(userInRole);
            }

            return View(users);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(List<UserInRoleViewModel> users,string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role == null)
                return NotFound();

            if (ModelState.IsValid)
            {
                foreach (var item in users)
                {
                    var user = await _userManager.FindByIdAsync(item.UserId);

                    if(user != null)
                    {
                        if (item.IsSelected && !(await _userManager.IsInRoleAsync(user, role.Name)))
                            await _userManager.AddToRoleAsync(user, role.Name);
                        else if (!item.IsSelected && (await _userManager.IsInRoleAsync(user, role.Name)))
                            await _userManager.RemoveFromRoleAsync(user, role.Name);
                    }
                }
                return RedirectToAction(nameof(Update), new {id = roleId});
            }

            return View(users);
        }
    }
}

Controllers/UsersController.cs
using Company.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Company.PL.Controllers
{
    [Authorize(Roles = "Admin, HR")]
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UsersController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string SearchValue = "") 
        {
            if (string.IsNullOrEmpty(SearchValue))
            {
                var users = _userManager.Users;
                return View(users);
            }
            else
            {
                var user = await _userManager.Users.Where(x => x.NormalizedEmail.Contains(SearchValue.ToUpper())).ToListAsync();
                return View(user);
            }
        }

        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
            if (id == null)
                return NotFound();

            var user = await _userManager.FindByIdAsync(id);

            if(user == null)
                return NotFound();

            return View(viewName, user);
        }

        public async Task<IActionResult> Update(string id)
        {
            return await Details(id, "Update");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id, ApplicationUser user)
        {
            if (id != user.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var appUser = await _userManager.FindByIdAsync(id);

                    appUser.UserName = user.UserName;
                    appUser.NormalizedUserName = user.UserName.ToUpper();
                    appUser.PhoneNumber = user.PhoneNumber;

                    var result = await _userManager.UpdateAsync(appUser);

                    if (result.Succeeded)
                        return RedirectToAction("Index");

                    foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(user);
        }

        public async Task<IActionResult> Delete(string id, ApplicationUser user)
        {
            if (id != user.Id)
                return BadRequest();

            try
            {
                var appUser = await _userManager.FindByIdAsync(id);

                var result = await _userManager.DeleteAsync(appUser);

                if (result.Succeeded)
                    return RedirectToAction("Index");

                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
}

Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>

<head>
  <title>Creative Colorlib SignUp Form</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <script type="application/x-javascript">
    addEventListener("load", function() {
      setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
      window.scrollTo(0, 1);
    }
  </script>
  <!-- Custom Theme files -->
  <link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
  <!-- //Custom Theme files -->
  <!-- web font -->
  <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
  <!-- //web font -->
</head>

<body>
  <!-- main -->
  <div class="main-w3layouts wrapper">
    <h1>@ViewData["Title"]</h1>
    @RenderBody()
    <!-- copyright -->
    <div class="colorlibcopy-agile">
      <p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
    </div>
    <!-- //copyright -->
    <ul class="colorlib-bubbles">
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
    </ul>
  </div>
  <!-- //main -->
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_ButtonsPartialView.cshtml
@model string

<td>
    <a class="btn btn-success" asp-action="Details" asp-route-id="@Model">
        <i class="fas fa-eye"></i> Details
    </a>
</td>
<td>
    <a class="btn btn-warning" asp-action="Update" asp-route-id="@Model">
        <i class="fas fa-edit"></i> Update
    </a>
</td>
<td>
    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model">
        <i class="fas fa-trash"></i> Delete
    </a>
</td>

Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCS2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCS2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCS2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>

                        @if(signManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                        }

                        <li class="nav-item ms-auto">
                            <a class="nav-link text-light btn btn-danger" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCS2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>